CREATE DATABASE IF NOT EXISTS todolist;
USE todolist;

CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON todolist.* TO 'user'@'%';

-- Logout and login is user above

USE todolist;

CREATE TABLE `todo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(400) DEFAULT NULL,
  `DONE` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
