version: '3.1'

services: 
  todo-server:
      build:
        context: ./
      environment:
        DB_URL: ${DB_USER}:${DB_PW}@tcp(database:3306)/${DB_NAME}
      container_name: todo-server
      ports:
        - "8080:8080"
      restart: unless-stopped
      links:
        - database
      depends_on:
        - database
      networks:
      - backend

  database:
    image: mysql/mysql-server:5.7
    container_name: todo-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PW}
    restart: unless-stopped
    volumes:
    - database:/var/lib/mysql
    networks:
      - backend

networks:
  backend:

volumes:
  database: