apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todo-ingress
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: api.todo.com
    http:
      paths:
      - path: /
        backend:
          serviceName: todo-server-service
          servicePort: 8080
