apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: todo-server
build:
  artifacts:
  - image: docker.io/somedevdude/todo-server
deploy:
  kubectl:
    manifests:
    - k8s-todo-server-deployment.yaml
portForward:
  - resourceType: deployment
    resourceName: todo-server
    port: 8080
    localPort: 8080
